In [1]:
import geopandas as gpd
import pandas as pd
# get median-standard-of-living shape file
median_ile_de_france = gpd.read_file('medianliving_and_jobdensity/MedianIle-de-France.shp')

In [2]:
median_ile_de_france.head()

,name,ref_INSEE,MED17,geometry
0,Paris,75056,27400,"POLYGON ((3758912.379 2894585.501, 3758949.844..."
1,Jouy-en-Josas,78322,33830,"POLYGON ((3747725.968 2879406.672, 3747713.484..."
2,Saclay,91534,32090,"POLYGON ((3747725.968 2879406.672, 3747719.983..."
3,Les Loges-en-Josas,78343,38890,"POLYGON ((3744704.931 2881572.655, 3744733.814..."
4,Buc,78117,33420,"POLYGON ((3744066.037 2883653.565, 3744082.210..."

In [3]:
job_density = pd.read_excel('job_density/base-cc-flores-2018.xlsx', sheet_name='COM', header=4)
job_density.head()

In [5]:
job_density = job_density[['CODGEO', 'Libellé commune ou ARM', 'Postes des Ets actifs fin 2018']]
job_density.columns = ['ref_INSEE', 'name', 'Job_density']
job_density.head()

In [8]:
median_and_jobs_ile_de_france = median_ile_de_france.merge(job_density.drop(columns=['name']), 
                                                           how='left', on='ref_INSEE')

In [11]:
median_and_jobs_ile_de_france.head()

,name,ref_INSEE,MED17,geometry,Job_density
0,Paris,75056,27400,"POLYGON ((3758912.379 2894585.501, 3758949.844...",1820029
1,Jouy-en-Josas,78322,33830,"POLYGON ((3747725.968 2879406.672, 3747713.484...",5348
2,Saclay,91534,32090,"POLYGON ((3747725.968 2879406.672, 3747719.983...",9795
3,Les Loges-en-Josas,78343,38890,"POLYGON ((3744704.931 2881572.655, 3744733.814...",829
4,Buc,78117,33420,"POLYGON ((3744066.037 2883653.565, 3744082.210...",8245
...,...,...,...,...,...
1247,Beautheil-Saints,77433,24970,"POLYGON ((3812801.931 2877640.930, 3812821.366...",110
1248,Chenoise-Cucharmoy,77109,20800,"POLYGON ((3816447.913 2856121.416, 3814709.993...",156
1249,Le Mérévillois,91390,23000,"POLYGON ((3736995.653 2830545.043, 3736924.654...",648
1250,Saint-Germain-en-Laye,78551,30970,"POLYGON ((3748952.187 2902755.688, 3747025.111...",17999
1251,Villemaréchal,77504,24890,"POLYGON ((3792759.896 2823371.114, 3792869.755...",48

In [12]:
# check for NaNs
median_and_jobs_ile_de_france.isnull().sum()

name           0
ref_INSEE      0
MED17          0
geometry       0
Job_density    0
dtype: int64

In [13]:
# save data as new shapefile 
#median_and_jobs_ile_de_france.to_file('medianliving_and_jobdensity/Ile-de-France.shp')

<ipython-input-13-2ba00bd5aba3>:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  median_and_jobs_ile_de_france.to_file('medianliving_and_jobdensity/Ile-de-France.shp')

## Now, the same for Paris City

In [14]:
median_paris = gpd.read_file('medianliving_and_jobdensity/MedianParis.shp')

In [15]:
median_paris

,name,ref_INSEE,MED17,geometry
0,Paris 16e Arrondissement,75116,38900,"POLYGON ((3755742.048 2892479.119, 3755753.797..."
1,Paris 17e Arrondissement,75117,30800,"POLYGON ((3758912.379 2894585.501, 3758949.844..."
2,Paris 15e Arrondissement,75115,30880,"POLYGON ((3754002.905 2887655.394, 3754190.319..."
3,Paris 7e Arrondissement,75107,43270,"POLYGON ((3757158.190 2890631.955, 3757190.735..."
4,Paris 14e Arrondissement,75114,27680,"POLYGON ((3756702.398 2886389.675, 3756704.144..."
5,Paris 12e Arrondissement,75112,27700,"POLYGON ((3764062.518 2886096.301, 3764048.150..."
6,Paris 6e Arrondissement,75106,39330,"POLYGON ((3759395.701 2889936.184, 3759411.648..."
7,Paris 10e Arrondissement,75110,26370,"POLYGON ((3761997.652 2892463.777, 3762007.874..."
8,Paris 20e Arrondissement,75120,21560,"POLYGON ((3765370.188 2888183.374, 3765370.817..."
9,Paris 13e Arrondissement,75113,24110,"POLYGON ((3760065.391 2885098.267, 3760054.258..."
10,Paris 18e Arrondissement,75118,22330,"POLYGON ((3762259.227 2894381.837, 3762588.043..."
11,Paris 11e Arrondissement,75111,27460,"POLYGON ((3762753.172 2891009.921, 3762815.493..."
12,Paris 9e Arrondissement,75109,33980,"POLYGON ((3760881.404 2892507.715, 3760885.117..."
13,Paris 2e Arrondissement,75102,31470,"POLYGON ((3760616.610 2891075.550, 3760627.055..."
14,Paris 19e Arrondissement,75119,20320,"POLYGON ((3762601.760 2894357.072, 3762693.771..."
15,Paris 4e Arrondissement,75104,31200,"POLYGON ((3760682.210 2890097.181, 3760687.944..."
16,Paris 1er Arrondissement,75101,32890,"POLYGON ((3759156.754 2891144.253, 3759165.971..."
17,Paris 3e Arrondissement,75103,32310,"POLYGON ((3761066.208 2890877.638, 3761070.191..."
18,Paris 8e Arrondissement,75108,41270,"POLYGON ((3759251.629 2892650.612, 3759249.426..."
19,Paris 5e Arrondissement,75105,33350,"POLYGON ((3760187.167 2889261.585, 3760356.283..."

In [16]:
job_density = pd.read_excel('job_density/base-cc-flores-2018.xlsx', sheet_name='ARM', header=4)

In [18]:
job_density = job_density[['CODGEO', 'Libellé commune ou ARM', 'Postes des Ets actifs fin 2018']]
job_density.columns = ['ref_INSEE', 'name', 'Job_density']
job_density.head()

  ref_INSEE                          name Job_density
0    CODGEO                        LIBGEO    ETPTOT18
1     13201  Marseille 1er Arrondissement       21665
2     13202   Marseille 2e Arrondissement       57068
3     13203   Marseille 3e Arrondissement       17302
4     13204   Marseille 4e Arrondissement        7711

In [19]:
median_and_jobs_paris = median_paris.merge(job_density.drop(columns=['name']), 
                                                           how='left', on='ref_INSEE')

In [20]:
median_and_jobs_paris

,name,ref_INSEE,MED17,geometry,Job_density
0,Paris 16e Arrondissement,75116,38900,"POLYGON ((3755742.048 2892479.119, 3755753.797...",105049
1,Paris 17e Arrondissement,75117,30800,"POLYGON ((3758912.379 2894585.501, 3758949.844...",109566
2,Paris 15e Arrondissement,75115,30880,"POLYGON ((3754002.905 2887655.394, 3754190.319...",156255
3,Paris 7e Arrondissement,75107,43270,"POLYGON ((3757158.190 2890631.955, 3757190.735...",78266
4,Paris 14e Arrondissement,75114,27680,"POLYGON ((3756702.398 2886389.675, 3756704.144...",79623
5,Paris 12e Arrondissement,75112,27700,"POLYGON ((3764062.518 2886096.301, 3764048.150...",113454
6,Paris 6e Arrondissement,75106,39330,"POLYGON ((3759395.701 2889936.184, 3759411.648...",53679
7,Paris 10e Arrondissement,75110,26370,"POLYGON ((3761997.652 2892463.777, 3762007.874...",84634
8,Paris 20e Arrondissement,75120,21560,"POLYGON ((3765370.188 2888183.374, 3765370.817...",56275
9,Paris 13e Arrondissement,75113,24110,"POLYGON ((3760065.391 2885098.267, 3760054.258...",114095
10,Paris 18e Arrondissement,75118,22330,"POLYGON ((3762259.227 2894381.837, 3762588.043...",59444
11,Paris 11e Arrondissement,75111,27460,"POLYGON ((3762753.172 2891009.921, 3762815.493...",67805
12,Paris 9e Arrondissement,75109,33980,"POLYGON ((3760881.404 2892507.715, 3760885.117...",130443
13,Paris 2e Arrondissement,75102,31470,"POLYGON ((3760616.610 2891075.550, 3760627.055...",75641
14,Paris 19e Arrondissement,75119,20320,"POLYGON ((3762601.760 2894357.072, 3762693.771...",77740
15,Paris 4e Arrondissement,75104,31200,"POLYGON ((3760682.210 2890097.181, 3760687.944...",69288
16,Paris 1er Arrondissement,75101,32890,"POLYGON ((3759156.754 2891144.253, 3759165.971...",83196
17,Paris 3e Arrondissement,75103,32310,"POLYGON ((3761066.208 2890877.638, 3761070.191...",30693
18,Paris 8e Arrondissement,75108,41270,"POLYGON ((3759251.629 2892650.612, 3759249.426...",220596
19,Paris 5e Arrondissement,75105,33350,"POLYGON ((3760187.167 2889261.585, 3760356.283...",54287

In [21]:
# save data as new shapefile 
#median_and_jobs_paris.to_file('medianliving_and_jobdensity/Paris_Arrondissements.shp')

<ipython-input-21-a15c7fd92670>:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  median_and_jobs_paris.to_file('medianliving_and_jobdensity/Paris_Arrondissements.shp')